print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/erichchu/Documents/WorldofMadness/World of Madness/Assets/Animations/orinjarun.mb"`)
{		
	file -o "/Users/erichchu/Documents/WorldofMadness/World of Madness/Assets/Animations/orinjarun.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/erichchu/Documents/WorldofMadness/World of Madness/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/erichchu/Documents/WorldofMadness/World of Madness/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/erichchu/Documents/WorldofMadness/World of Madness/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
